from __future__ import annotations

from framework.harness.subagents.context import SubAgentContextBuilder
from framework.harness.subagents.fake import FakeSubAgentContextBuilder, FakeSubAgentRuntime, FakeSubAgentWorker, fake_subagent_spec
from framework.harness.subagents.gates import (
    FakeSubAgentGateSuite,
    SubAgentBudgetGate,
    SubAgentContextBoundaryGate,
    SubAgentGateResult,
    SubAgentHandoffSchemaGate,
    SubAgentInputSchemaGate,
    SubAgentMemoryNamespaceGate,
    SubAgentOutputSchemaGate,
    SubAgentToolAllowlistGate,
    SubAgentTranscriptGate,
)
from framework.harness.subagents.handoff import verify_handoff
from framework.harness.subagents.models import (
    FORBIDDEN_SUBAGENT_CONTEXT_KEYS,
    FORBIDDEN_SUBAGENT_RESULT_KEYS,
    SubAgentContextEnvelope,
    SubAgentHandoff,
    SubAgentInvocation,
    SubAgentResult,
    SubAgentSpec,
    SubAgentStatus,
)
from framework.harness.subagents.observability import (
    SUBAGENT_TRANSCRIPT_BYTES,
    SUBAGENT_TRANSCRIPT_COMMIT_FAILED,
    SUBAGENT_TRANSCRIPT_COMMIT_LATENCY_MS,
    SUBAGENT_TRANSCRIPT_COMMIT_SUCCEEDED,
    SUBAGENT_TRANSCRIPT_CONFLICT,
    SUBAGENT_TRANSCRIPT_CORRUPT,
    SUBAGENT_TRANSCRIPT_RECOVERY_REUSED_TOTAL,
    SUBAGENT_TRANSCRIPT_VERIFY_FAILED,
    SubAgentTranscriptObservation,
    SubAgentTranscriptObservationSink,
)
from framework.harness.subagents.policy import SubAgentBudget, SubAgentMemoryPolicy, SubAgentToolPolicy
from framework.harness.subagents.runtime import (
    SubAgentRuntime,
    subagent_attempt_identity,
)
from framework.harness.subagents.transcript import (
    DEFAULT_MAX_BUNDLE_BYTES,
    DEFAULT_MAX_OUTPUT_BYTES,
    DEFAULT_MAX_TRANSCRIPT_BYTES,
    FakeSubAgentTranscriptStore,
    SubAgentAttemptIdentity,
    SubAgentContextEvidence,
    SubAgentOutputDocument,
    SubAgentTranscript,
    SubAgentTranscriptConflictError,
    SubAgentTranscriptCorruptError,
    SubAgentTranscriptReceipt,
    SubAgentTranscriptStoreError,
    SubAgentTranscriptStorePort,
)

__all__ = [
    "FORBIDDEN_SUBAGENT_CONTEXT_KEYS",
    "FORBIDDEN_SUBAGENT_RESULT_KEYS",
    "FakeSubAgentContextBuilder",
    "FakeSubAgentGateSuite",
    "FakeSubAgentRuntime",
    "FakeSubAgentTranscriptStore",
    "DEFAULT_MAX_BUNDLE_BYTES",
    "DEFAULT_MAX_OUTPUT_BYTES",
    "DEFAULT_MAX_TRANSCRIPT_BYTES",
    "FakeSubAgentWorker",
    "SubAgentBudget",
    "SubAgentBudgetGate",
    "SubAgentContextBoundaryGate",
    "SubAgentContextBuilder",
    "SubAgentContextEnvelope",
    "SubAgentGateResult",
    "SubAgentHandoff",
    "SubAgentHandoffSchemaGate",
    "SubAgentInputSchemaGate",
    "SubAgentInvocation",
    "SubAgentMemoryNamespaceGate",
    "SubAgentMemoryPolicy",
    "SubAgentOutputSchemaGate",
    "SubAgentResult",
    "SubAgentRuntime",
    "SubAgentSpec",
    "SubAgentStatus",
    "SubAgentToolAllowlistGate",
    "SubAgentToolPolicy",
    "SubAgentTranscript",
    "SubAgentAttemptIdentity",
    "SubAgentContextEvidence",
    "SubAgentOutputDocument",
    "SubAgentTranscriptConflictError",
    "SubAgentTranscriptCorruptError",
    "SubAgentTranscriptReceipt",
    "SubAgentTranscriptStoreError",
    "SubAgentTranscriptStorePort",
    "SubAgentTranscriptGate",
    "SubAgentTranscriptObservation",
    "SubAgentTranscriptObservationSink",
    "SUBAGENT_TRANSCRIPT_BYTES",
    "SUBAGENT_TRANSCRIPT_COMMIT_FAILED",
    "SUBAGENT_TRANSCRIPT_COMMIT_LATENCY_MS",
    "SUBAGENT_TRANSCRIPT_COMMIT_SUCCEEDED",
    "SUBAGENT_TRANSCRIPT_CONFLICT",
    "SUBAGENT_TRANSCRIPT_CORRUPT",
    "SUBAGENT_TRANSCRIPT_RECOVERY_REUSED_TOTAL",
    "SUBAGENT_TRANSCRIPT_VERIFY_FAILED",
    "fake_subagent_spec",
    "verify_handoff",
    "subagent_attempt_identity",
]
