from __future__ import annotations

from interfaces.api import create_app


def test_api_router_parity_keeps_current_paths_registered() -> None:
    app = create_app(audit_emitter_factory=None)
    paths = {route.path for route in app.routes}

    expected_paths = {
        "/health",
        "/health/live",
        "/health/ready",
        "/health/dependencies",
        "/api/v1/runs",
        "/api/v1/runs/daily",
        "/api/v1/runs/weekly",
        "/api/v1/runs/catalog/health",
        "/api/v1/runs/compare",
        "/api/v1/runs/{run_id}",
        "/api/v1/runs/{run_id}/manifest",
        "/api/v1/runs/{run_id}/events",
        "/api/v1/runs/{run_id}/steps",
        "/api/v1/runs/{run_id}/events/stream",
        "/api/v1/runs/{run_id}/progress",
        "/api/v1/runs/{run_id}/replay",
        "/api/v1/runs/{run_id}/diagnostics",
        "/api/v1/runs/{run_id}/health",
        "/api/v1/runs/{run_id}/lineage",
        "/api/v1/runs/{run_id}/lineage/upstream",
        "/api/v1/runs/{run_id}/lineage/downstream",
        "/api/v1/runs/{run_id}/artifacts",
        "/api/v1/runs/{run_id}/artifacts/{artifact_key}",
        "/api/v1/runs/{run_id}/operations/cancel",
        "/api/v1/runs/{run_id}/operations/rerun-from-step",
        "/api/v1/runs/{run_id}/operations/resume-with-patch",
        "/api/v1/runs/{run_id}/operations/skip-step",
        "/api/v1/runs/{run_id}/operations/mark-blocked-resolved",
        "/api/v1/artifacts",
        "/api/v1/artifacts/{artifact_id}",
        "/api/v1/reports/latest",
        "/api/v1/reports",
        "/api/v1/reports/{report_id}",
        "/api/v1/reports/{report_id}/markdown",
        "/api/v1/reports/{report_id}/quality",
        "/api/v1/reports/{report_id}/request-review",
        "/api/v1/reports/{report_id}/publish",
        "/api/v1/search/reports",
        "/api/v1/memory/search",
        "/api/v1/memory/reindex",
        "/api/v1/memory/{document_id}",
        "/api/v1/sources",
        "/api/v1/sources/health",
        "/api/v1/sources/validation",
        "/api/v1/sources/categories",
        "/api/v1/sources/priorities",
        "/api/v1/sources/{source_id}",
        "/api/v1/sources/{source_id}/probe",
        "/api/v1/sources/fetch",
        "/api/v1/sources/fetch-category",
        "/api/v1/sources/fetch-priority",
        "/api/v1/sources/fetch-topic",
        "/api/v1/sources/arxiv/fetch",
        "/api/v1/sources/github/releases",
        "/api/v1/papers",
        "/api/v1/workers",
        "/api/v1/workers/{worker_id}",
        "/api/v1/queues",
        "/api/v1/approvals",
        "/api/v1/approvals/{approval_id}",
        "/api/v1/approvals/{approval_id}/resume-context",
        "/api/v1/approvals/{approval_id}/resume-workflow",
        "/api/v1/approvals/{approval_id}/approve",
        "/api/v1/approvals/{approval_id}/reject",
        "/api/v1/approvals/{approval_id}/modify",
        "/api/v1/storage/metrics",
        "/api/v1/storage/retention/plan",
        "/api/v1/mcp/catalog",
        "/api/v1/mcp/capabilities",
        "/api/v1/mcp/manifest",
        "/api/v1/schedules",
        "/api/v1/schedules/daily",
        "/api/v1/schedules/papers/ingest",
        "/api/v1/schedules/tick",
        "/api/v1/schedules/{schedule_id}/trigger",
        "/api/v1/entities",
        "/api/v1/entities/{entity_id}/enable",
        "/api/v1/entities/{entity_id}/disable",
        "/api/v1/entities/{entity_id}",
        "/api/v1/entities/{entity_id}/report-matches",
        "/api/v1/subscriptions",
        "/api/v1/subscriptions/{subscription_id}/enable",
        "/api/v1/subscriptions/{subscription_id}/disable",
        "/api/v1/subscriptions/{subscription_id}",
        "/api/v1/admin/diagnose",
    }

    assert expected_paths <= paths
