from __future__ import annotations

from typing import Any

from business.research.document.models import PaperChunk


def paper_chunk_to_context_metadata(chunk: PaperChunk) -> dict[str, Any]:
    return {
        "section_role": chunk.section_role,
        "section_index": chunk.section_index,
        "chunk_type": chunk.chunk_type,
        "parent_chunk_id": chunk.parent_chunk_id,
        "has_formula": chunk.has_formula,
        "formula_latex": chunk.formula_latex,
        "has_figure": chunk.has_figure,
        "figure_id": chunk.figure_id,
        "has_table": chunk.has_table,
        "table_id": chunk.metadata.get("table_id", ""),
        "image_ref": chunk.metadata.get("image_ref", ""),
        "source_locator": chunk.metadata.get("source_locator", ""),
        "caption_source_locator": chunk.metadata.get("caption_source_locator", ""),
        "page": chunk.metadata.get("page"),
        "pdf_rect": chunk.metadata.get("pdf_rect"),
        "caption_pdf_rect": chunk.metadata.get("caption_pdf_rect"),
        "content_sources": chunk.metadata.get("content_sources", []),
        "ocr_attempted": chunk.metadata.get("ocr_attempted", False),
        "ocr_chars": chunk.metadata.get("ocr_chars", 0),
        "ocr_error": chunk.metadata.get("ocr_error", ""),
        "ocr_text_source": chunk.metadata.get("ocr_text_source", ""),
        "text_score": chunk.metadata.get("text_score"),
        "visual_score": chunk.metadata.get("visual_score"),
        "fused_score": chunk.metadata.get("fused_score"),
        "fusion_strategy": chunk.metadata.get("fusion_strategy", ""),
        "visual_hit": chunk.metadata.get("visual_hit", False),
        "expanded_from_chunk_id": chunk.metadata.get("expanded_from_chunk_id", ""),
        "expansion_reason": chunk.metadata.get("expansion_reason", ""),
        "expansion_edge": chunk.metadata.get("expansion_edge", ""),
        "expansion_rank": chunk.metadata.get("expansion_rank"),
        "evidence_group_id": chunk.metadata.get("evidence_group_id", ""),
        "evidence_group_role": chunk.metadata.get("evidence_group_role", ""),
        "evidence_pack_expansion": chunk.metadata.get("evidence_pack_expansion", False),
        "table_context_rerank_score": chunk.metadata.get("table_context_rerank_score"),
        "table_context_rerank_strategy": chunk.metadata.get("table_context_rerank_strategy", ""),
        "parent_expansion_reason": chunk.metadata.get("parent_expansion_reason", ""),
        "parent_anchor_child_id": chunk.metadata.get("parent_anchor_child_id", ""),
        "parent_snippet": chunk.metadata.get("parent_snippet", False),
        "parent_snippet_strategy": chunk.metadata.get("parent_snippet_strategy", ""),
        "source_parent_chunk_id": chunk.metadata.get("source_parent_chunk_id", ""),
        "parent_rerank_score": chunk.metadata.get("parent_rerank_score"),
        "parent_rerank_strategy": chunk.metadata.get("parent_rerank_strategy", ""),
        "parent_child_relevance_score": chunk.metadata.get("parent_child_relevance_score"),
        "parent_relevance_score": chunk.metadata.get("parent_relevance_score"),
        "parent_section_heading_score": chunk.metadata.get("parent_section_heading_score"),
        "parent_position_score": chunk.metadata.get("parent_position_score"),
        "parent_final_score": chunk.metadata.get("parent_final_score"),
        "parent_score_strategy": chunk.metadata.get("parent_score_strategy", ""),
        "parent_score_weights": chunk.metadata.get("parent_score_weights", {}),
        "claim_index_hit": chunk.metadata.get("claim_index_hit", False),
        "claim_index_score": chunk.metadata.get("claim_index_score"),
        "claim_id": chunk.metadata.get("claim_id", ""),
        "claim_text": chunk.metadata.get("claim_text", ""),
        "claim_type": chunk.metadata.get("claim_type", ""),
        "claim_source_locator": chunk.metadata.get("claim_source_locator", ""),
        "title_score": chunk.metadata.get("title_score"),
        "abstract_score": chunk.metadata.get("abstract_score"),
        "caption_score": chunk.metadata.get("caption_score"),
        "equation_score": chunk.metadata.get("equation_score"),
        "body_score": chunk.metadata.get("body_score"),
        "field_score": chunk.metadata.get("field_score"),
        "field_score_weights": chunk.metadata.get("field_score_weights", {}),
        "field_score_strategy": chunk.metadata.get("field_score_strategy", ""),
        "title_embedding_score": chunk.metadata.get("title_embedding_score"),
        "abstract_embedding_score": chunk.metadata.get("abstract_embedding_score"),
        "caption_embedding_score": chunk.metadata.get("caption_embedding_score"),
        "equation_embedding_score": chunk.metadata.get("equation_embedding_score"),
        "body_embedding_score": chunk.metadata.get("body_embedding_score"),
        "field_embedding_score": chunk.metadata.get("field_embedding_score"),
        "field_embedding_scores": chunk.metadata.get("field_embedding_scores", {}),
        "field_embedding_hits": chunk.metadata.get("field_embedding_hits", []),
        "best_embedding_field": chunk.metadata.get("best_embedding_field", ""),
        "field_embedding_strategy": chunk.metadata.get("field_embedding_strategy", ""),
        "field_rerank_score": chunk.metadata.get("field_rerank_score"),
        "field_rerank_strategy": chunk.metadata.get("field_rerank_strategy", ""),
        "best_matching_field": chunk.metadata.get("best_matching_field", ""),
        "element_label_boost": chunk.metadata.get("element_label_boost"),
        "graph_score": chunk.metadata.get("graph_score"),
        "child_score_strategy": chunk.metadata.get("child_score_strategy", ""),
        "child_score_components": chunk.metadata.get("child_score_components", {}),
        "field_text_available_fields": chunk.metadata.get("field_text_available_fields", ()),
        "field_text_sources": chunk.metadata.get("field_text_sources", {}),
        "content_span_unit": chunk.metadata.get("content_span_unit", ""),
        "main_span": chunk.metadata.get("main_span", {}),
        "overlap_spans": chunk.metadata.get("overlap_spans", []),
        "child_semantic_score": chunk.metadata.get("child_semantic_score"),
        "child_position_score": chunk.metadata.get("child_position_score"),
        "child_final_score": chunk.metadata.get("child_final_score"),
        "child_score_weights": chunk.metadata.get("child_score_weights", {}),
        "row_start": chunk.metadata.get("row_start"),
        "row_end": chunk.metadata.get("row_end"),
        "parent_table_chunk_id": chunk.metadata.get("parent_table_chunk_id", ""),
        "is_table_row_group": chunk.metadata.get("is_table_row_group", False),
    }


__all__ = ["paper_chunk_to_context_metadata"]
