from __future__ import annotations

from infrastructure.storage.persistence.local_json_adapter import LocalJsonPersistenceAdapter
from infrastructure.storage.persistence.records import (
    GraphRunRecord,
    ReportRecord,
    RunPersistenceBatch,
)
from infrastructure.storage.persistence.repository import (
    PersistenceRepository,
    RunPersistenceInput,
    claim_records_from_result,
    claim_records_from_input,
    evidence_item_records_from_result,
    evidence_item_records_from_input,
    persist_run_input,
    persist_run_result,
    quality_result_record_from_result,
    quality_result_record_from_input,
    report_record_from_result,
    report_record_from_input,
    repository_from_env,
    run_persistence_batch_from_result,
    run_persistence_batch_from_input,
    run_persistence_input_from_output,
    run_persistence_input_from_result,
    source_item_records_from_result,
    source_item_records_from_input,
    graph_run_record_from_result,
    graph_run_record_from_input,
)


__all__ = [
    "LocalJsonPersistenceAdapter",
    "PersistenceRepository",
    "ReportRecord",
    "RunPersistenceInput",
    "RunPersistenceBatch",
    "GraphRunRecord",
    "claim_records_from_result",
    "claim_records_from_input",
    "evidence_item_records_from_result",
    "evidence_item_records_from_input",
    "persist_run_input",
    "persist_run_result",
    "quality_result_record_from_result",
    "quality_result_record_from_input",
    "report_record_from_result",
    "report_record_from_input",
    "repository_from_env",
    "run_persistence_batch_from_result",
    "run_persistence_batch_from_input",
    "run_persistence_input_from_output",
    "run_persistence_input_from_result",
    "source_item_records_from_result",
    "source_item_records_from_input",
    "graph_run_record_from_result",
    "graph_run_record_from_input",
]
