"""Compatibility module for legacy core.framework.specs.workflow_spec imports."""

from framework.specs import (
    ArtifactPolicySpec,
    EdgeCondition,
    EdgeConditionSpec,
    EdgeSpec,
    FailurePolicySpec,
    LineagePolicySpec,
    QualityPolicySpec,
    ResourcePolicySpec,
    RetryPolicySpec,
    StepSpec,
    StepStatus,
    StepType,
    TimeoutPolicySpec,
    ValidationErrorItem,
    ValidationResult,
    ValidationWarningItem,
    WorkflowPolicySpec,
    WorkflowSpec,
    WorkflowSpecError,
    WorkflowSpecRegistry,
    WorkflowSpecValidator,
    WorkflowStatus,
    WorkflowTriggerSpec,
    WorkflowTriggerType,
)

__all__ = [
    "ArtifactPolicySpec",
    "EdgeCondition",
    "EdgeConditionSpec",
    "EdgeSpec",
    "FailurePolicySpec",
    "LineagePolicySpec",
    "QualityPolicySpec",
    "ResourcePolicySpec",
    "RetryPolicySpec",
    "StepSpec",
    "StepStatus",
    "StepType",
    "TimeoutPolicySpec",
    "ValidationErrorItem",
    "ValidationResult",
    "ValidationWarningItem",
    "WorkflowPolicySpec",
    "WorkflowSpec",
    "WorkflowSpecError",
    "WorkflowSpecRegistry",
    "WorkflowSpecValidator",
    "WorkflowStatus",
    "WorkflowTriggerSpec",
    "WorkflowTriggerType",
]
