"""Shared framework primitives and helpers."""

from framework.shared.attempts import (
    AttemptCancelledError,
    AttemptContext,
    AttemptCleanupError,
    AttemptFinalization,
    AttemptIdentity,
    AttemptLifecycleEmissionError,
    AttemptLifecycleSink,
    AttemptOutcome,
    AttemptReservation,
    AttemptState,
    AttemptSupervisor,
    CompositeAttemptLifecycleSink,
    DeadlineAdmissionPolicy,
    DeadlineAdmissionRejectedError,
    ExecutionLimits,
    LocalRetryBudget,
    LocalRetryBudgetExhaustedError,
    OperationContext,
    ParentCancelledBeforeStartError,
    RetryCreditExhaustedError,
    RetryCreditLedger,
    bind_attempt_context,
    current_attempt_context,
)
from framework.shared.errors import (
    BoundaryViolationError,
    ConfigurationError,
    DependencyError,
    FrameworkError,
    RuntimeExecutionError,
    ValidationError,
)
from framework.shared.attempt_events import (
    attempt_rejection_event_payload,
    attempt_started_event_payload,
    attempt_terminal_event_payload,
)
from framework.shared.attempt_history import (
    ATTEMPT_HISTORY_PROJECTION_SCHEMA,
    LEGACY_ATTEMPT_SEMANTICS,
    SCOPE_AWARE_ATTEMPT_SEMANTICS,
    AttemptHistoryProjection,
    decode_attempt_history,
    decode_attempt_history_many,
)
from framework.shared.hashing import hash_bytes, hash_text, short_hash, stable_hash
from framework.shared.graph_identity import (
    GraphExecutionIdentity,
    GraphIdentity,
    GraphRunIdentity,
    GraphStageIdentity,
    coerce_graph_identity,
)
from framework.shared.ids import RunId, StepId, TaskId, generate_id, normalize_id, stable_id
from framework.shared.json import json_loads, stable_json_dumps, to_jsonable
from framework.shared.pagination import PageRequest, PageResult
from framework.shared.redaction import (
    DEFAULT_SENSITIVE_KEY_TOKENS,
    REDACTED_VALUE,
    RedactionRule,
    Redactor,
    contains_redacted_value,
    redact_sensitive_values,
)
from framework.shared.result import ErrorDetail, Result
from framework.shared.serialization import JsonDataclassSerializer, Serializable, Serializer
from framework.shared.status import RuntimeStatus
from framework.shared.time import duration_ms, ensure_utc, format_datetime, parse_datetime, utc_now
from framework.shared.typing import JsonDict, JsonValue, Metadata, ensure_dict, ensure_list, optional_str

__all__ = [
    "AttemptCancelledError",
    "AttemptContext",
    "AttemptCleanupError",
    "AttemptFinalization",
    "AttemptIdentity",
    "AttemptLifecycleEmissionError",
    "AttemptLifecycleSink",
    "AttemptOutcome",
    "AttemptReservation",
    "AttemptState",
    "AttemptSupervisor",
    "CompositeAttemptLifecycleSink",
    "attempt_rejection_event_payload",
    "attempt_started_event_payload",
    "attempt_terminal_event_payload",
    "ATTEMPT_HISTORY_PROJECTION_SCHEMA",
    "LEGACY_ATTEMPT_SEMANTICS",
    "SCOPE_AWARE_ATTEMPT_SEMANTICS",
    "AttemptHistoryProjection",
    "DeadlineAdmissionPolicy",
    "DeadlineAdmissionRejectedError",
    "ExecutionLimits",
    "LocalRetryBudget",
    "LocalRetryBudgetExhaustedError",
    "OperationContext",
    "ParentCancelledBeforeStartError",
    "RetryCreditExhaustedError",
    "RetryCreditLedger",
    "BoundaryViolationError",
    "ConfigurationError",
    "DEFAULT_SENSITIVE_KEY_TOKENS",
    "DependencyError",
    "ErrorDetail",
    "FrameworkError",
    "GraphRunIdentity",
    "GraphStageIdentity",
    "GraphExecutionIdentity",
    "GraphIdentity",
    "coerce_graph_identity",
    "JsonDataclassSerializer",
    "JsonDict",
    "JsonValue",
    "Metadata",
    "PageRequest",
    "PageResult",
    "REDACTED_VALUE",
    "RedactionRule",
    "Redactor",
    "Result",
    "RunId",
    "RuntimeExecutionError",
    "RuntimeStatus",
    "Serializable",
    "Serializer",
    "StepId",
    "TaskId",
    "ValidationError",
    "bind_attempt_context",
    "contains_redacted_value",
    "current_attempt_context",
    "duration_ms",
    "decode_attempt_history",
    "decode_attempt_history_many",
    "ensure_dict",
    "ensure_list",
    "ensure_utc",
    "format_datetime",
    "generate_id",
    "hash_bytes",
    "hash_text",
    "json_loads",
    "normalize_id",
    "optional_str",
    "parse_datetime",
    "redact_sensitive_values",
    "short_hash",
    "stable_hash",
    "stable_id",
    "stable_json_dumps",
    "to_jsonable",
    "utc_now",
]
