"""Typed interface-layer models shared by API, MCP, SDK, and webhooks."""

from interfaces.models.actor import ActorContext, actor_context_from_headers
from interfaces.models.audit import AuditRecord
from interfaces.models.common import ApiActionResult, PageResult, Pagination
from interfaces.models.contracts import (
    SCHEMA_VERSION,
    ApiError,
    ApiResponse,
    ApprovalDecisionRequest,
    ApprovalModifyRequest,
    ApprovalResumeContextRequest,
    ApprovalSubmitRequest,
    ArxivSourceFetchRequest,
    ArtifactRef,
    DailyRunRequest,
    DailyScheduleRequest,
    EntityCreateRequest,
    GithubReleaseFetchRequest,
    ManualScheduleTriggerRequest,
    MemoryReindexRequest,
    MemorySearchRequest,
    ReportActionRequest,
    ReportDetail,
    ReportSummary,
    RunRequest,
    RunResponse,
    ScheduleTickRequest,
    SourceProbeRequest,
    TopicSubscriptionCreateRequest,
    WeeklyRunRequest,
)

__all__ = [
    "SCHEMA_VERSION",
    "ActorContext",
    "ApiError",
    "AuditRecord",
    "ApiActionResult",
    "ApiResponse",
    "ApprovalDecisionRequest",
    "ApprovalModifyRequest",
    "ApprovalResumeContextRequest",
    "ApprovalSubmitRequest",
    "ArxivSourceFetchRequest",
    "ArtifactRef",
    "DailyRunRequest",
    "DailyScheduleRequest",
    "EntityCreateRequest",
    "GithubReleaseFetchRequest",
    "ManualScheduleTriggerRequest",
    "MemoryReindexRequest",
    "MemorySearchRequest",
    "PageResult",
    "Pagination",
    "ReportActionRequest",
    "ReportDetail",
    "ReportSummary",
    "RunRequest",
    "RunResponse",
    "ScheduleTickRequest",
    "SourceProbeRequest",
    "TopicSubscriptionCreateRequest",
    "WeeklyRunRequest",
    "actor_context_from_headers",
]
