from __future__ import annotations

from framework.harness.rag.context_pack_assembler import FakeRAGContextPackAssembler, RAGContextPackAssembler
from framework.harness.rag.evidence_typing import EvidenceTypeResolver, MetadataKeyEvidenceTypeResolver
from framework.harness.rag.fake import (
    FakeRAGGateSuite,
    FakeRAGPlanner,
    FakeRAGSessionController,
    fake_rag_session_spec,
    fake_reader_repair_memory,
    fake_research_evidence_packs,
)
from framework.harness.rag.kernel_evidence_adapter import KernelRAGRetrieverHarnessAdapter, evidence_candidate_from_rag_evidence
from framework.harness.rag.gates import (
    RAGEvidenceConflictGate,
    RAGEvidenceCoverageGate,
    RAGEvidenceGateResult,
    RAGBudgetGate,
    RAGContextSizeGate,
    RAGGateResult,
    RAGGateSuite,
    RAGLineageGate,
    RAGMemoryRelevanceGate,
    RAGPlanSchemaGate,
    RAGQueryDedupGate,
    RAGScopeGate,
    RAGSourceQualityGate,
    RAGToolAllowlistGate,
    failed_gate_dicts,
    validate_rag_evidence_refs,
)
from framework.harness.rag.models import (
    FORBIDDEN_RAG_PLAN_KEYS,
    EvidenceCandidate,
    RAGBudget,
    RAGBudgetSnapshot,
    RAGContextPack,
    RAGSessionRequest,
    RAGSessionSpec,
    RAGSessionStatus,
    RAGTranscript,
    RetrievalGoal,
    RetrievalOperation,
    RetrievalPlanCandidate,
    RetrievalStepResult,
    RetrievalStepSpec,
    ensure_jsonable_rag_model,
)
from framework.harness.rag.planner import DeterministicRAGPlanner, RAGPlanner, WorkerRAGPlanner
from framework.harness.rag.policy import RAGDecision, RAGDecisionType, RAGExecutionPolicy, budget_exceeded, normalize_query
from framework.harness.rag.session import BoundedRAGSessionController, RAGSessionController, RAGSessionResult, RAGSessionState
from framework.harness.rag.source_verifier import FakeSourceVerifier, SourceVerificationResult, SourceVerifier

__all__ = [
    "FORBIDDEN_RAG_PLAN_KEYS",
    "BoundedRAGSessionController",
    "DeterministicRAGPlanner",
    "EvidenceCandidate",
    "EvidenceTypeResolver",
    "FakeRAGContextPackAssembler",
    "FakeRAGGateSuite",
    "FakeRAGPlanner",
    "FakeRAGSessionController",
    "FakeSourceVerifier",
    "KernelRAGRetrieverHarnessAdapter",
    "MetadataKeyEvidenceTypeResolver",
    "RAGEvidenceConflictGate",
    "RAGEvidenceCoverageGate",
    "RAGEvidenceGateResult",
    "RAGBudget",
    "RAGBudgetGate",
    "RAGBudgetSnapshot",
    "RAGContextPack",
    "RAGContextPackAssembler",
    "RAGContextSizeGate",
    "RAGDecision",
    "RAGDecisionType",
    "RAGExecutionPolicy",
    "RAGGateResult",
    "RAGGateSuite",
    "RAGLineageGate",
    "RAGMemoryRelevanceGate",
    "RAGPlanSchemaGate",
    "RAGPlanner",
    "RAGQueryDedupGate",
    "RAGScopeGate",
    "RAGSessionController",
    "RAGSessionRequest",
    "RAGSessionResult",
    "RAGSessionSpec",
    "RAGSessionState",
    "RAGSessionStatus",
    "RAGSourceQualityGate",
    "RAGToolAllowlistGate",
    "RAGTranscript",
    "RetrievalGoal",
    "RetrievalOperation",
    "RetrievalPlanCandidate",
    "RetrievalStepResult",
    "RetrievalStepSpec",
    "SourceVerificationResult",
    "SourceVerifier",
    "WorkerRAGPlanner",
    "budget_exceeded",
    "evidence_candidate_from_rag_evidence",
    "ensure_jsonable_rag_model",
    "failed_gate_dicts",
    "fake_rag_session_spec",
    "fake_reader_repair_memory",
    "fake_research_evidence_packs",
    "normalize_query",
    "validate_rag_evidence_refs",
]
