from __future__ import annotations

from framework.specs import EdgeSpec, StepSpec, WorkflowSpec
from business.boards.cross_board.workflows.daily_intelligence.profiles import LEGACY_DAILY_WORKFLOW_ID, PROFILE_LIVE, PROFILE_LIVE_OFFLINE
WORKFLOW_ID = LEGACY_DAILY_WORKFLOW_ID
WORKFLOW_VERSION = "0.1.0"


def build_daily_intelligence_workflow(profile: str) -> WorkflowSpec:
    return WorkflowSpec(
        workflow_id=WORKFLOW_ID,
        name="Daily Intelligence Live",
        version=WORKFLOW_VERSION,
        description="Daily intelligence workflow for live and live-offline profiles.",
        start_step_id="collect_sources",
        terminal_step_ids=["quality_gate"],
        steps=[
            StepSpec(
                step_id="collect_sources",
                implementation="daily.collect_sources",
                read_keys=["request"],
                write_keys=[
                    "raw_items",
                    "source_errors",
                    "skipped_sources",
                    "failed_sources",
                    "source_fetch_requests",
                    "source_fetch_results",
                    "source_health_updates",
                    "source_health_report",
                    "source_events",
                    "source_pipeline_metrics",
                    "source_connector_dispatch_report",
                    "source_error_policy_report",
                    "source_fallback_report",
                    "source_selection_report",
                    "source_coverage_report",
                ],
                required_output_keys=[
                    "raw_items",
                    "source_errors",
                    "skipped_sources",
                    "failed_sources",
                    "source_fetch_requests",
                    "source_fetch_results",
                    "source_health_updates",
                    "source_health_report",
                    "source_events",
                    "source_pipeline_metrics",
                    "source_connector_dispatch_report",
                    "source_error_policy_report",
                    "source_fallback_report",
                    "source_selection_report",
                    "source_coverage_report",
                ],
            ),
            StepSpec(
                step_id="require_sources",
                implementation="daily.require_sources",
                read_keys=["raw_items", "source_errors"],
                write_keys=["source_collection_status"],
                required_output_keys=["source_collection_status"],
            ),
            StepSpec(
                step_id="normalize_sources",
                implementation="daily.normalize_sources",
                read_keys=["raw_items", "source_errors", "source_events", "source_pipeline_metrics"],
                write_keys=["normalized_items", "source_errors", "source_events", "source_pipeline_metrics"],
                required_output_keys=["normalized_items", "source_errors", "source_events", "source_pipeline_metrics"],
            ),
            StepSpec(
                step_id="deduplicate_sources",
                implementation="daily.deduplicate_sources",
                read_keys=["normalized_items", "source_errors", "source_events", "source_pipeline_metrics"],
                write_keys=[
                    "deduplicated_items",
                    "source_errors",
                    "source_duplicate_groups",
                    "source_events",
                    "source_pipeline_metrics",
                ],
                required_output_keys=[
                    "deduplicated_items",
                    "source_errors",
                    "source_duplicate_groups",
                    "source_events",
                    "source_pipeline_metrics",
                ],
            ),
            StepSpec(
                step_id="rank_sources",
                implementation="daily.rank_sources",
                read_keys=[
                    "deduplicated_items",
                    "request",
                    "source_errors",
                    "skipped_sources",
                    "failed_sources",
                    "source_selection_report",
                    "source_events",
                    "source_pipeline_metrics",
                ],
                write_keys=[
                    "ranked_items",
                    "source_errors",
                    "source_events",
                    "source_pipeline_metrics",
                    "source_coverage_report",
                    "source_quality_scores",
                    "source_quality_summary_report",
                    "source_ranking_scores",
                    "source_freshness_report",
                    "source_traceability_report",
                    "source_governance_report",
                ],
                required_output_keys=[
                    "ranked_items",
                    "source_errors",
                    "source_events",
                    "source_pipeline_metrics",
                    "source_coverage_report",
                    "source_quality_scores",
                    "source_quality_summary_report",
                    "source_ranking_scores",
                    "source_freshness_report",
                    "source_traceability_report",
                    "source_governance_report",
                ],
            ),
            StepSpec(
                step_id="build_evidence",
                implementation="daily.build_evidence",
                read_keys=["ranked_items"],
                write_keys=[
                    "evidence_bundle",
                    "evidence_scores",
                    "candidate_claims",
                    "verified_findings",
                    "quality_events",
                ],
                required_output_keys=[
                    "evidence_bundle",
                    "evidence_scores",
                    "candidate_claims",
                    "verified_findings",
                    "quality_events",
                ],
            ),
            StepSpec(
                step_id="draft_report",
                implementation="daily.draft_report",
                read_keys=["request", "evidence_bundle", "source_errors", "source_pipeline_metrics"],
                write_keys=["report_draft", "memory_context"],
                required_output_keys=["report_draft"],
            ),
            StepSpec(
                step_id="quality_gate",
                implementation="daily.quality_gate",
                read_keys=["report_draft", "evidence_bundle", "verified_findings", "quality_events"],
                write_keys=[
                    "citation_check_result",
                    "editor_review",
                    "support_matrix",
                    "report_quality_summary",
                    "quality_events",
                    "quality_gate_metrics",
                    "quality_result",
                    "quality_route",
                    "rewrite_policy",
                    "rewrite_instructions",
                    "memory_quality_result",
                    "rewritten_report_draft",
                    "human_review_request",
                    "final_report",
                    "report_markdown",
                    "blocked_report",
                ],
                required_output_keys=[
                    "citation_check_result",
                    "editor_review",
                    "support_matrix",
                    "report_quality_summary",
                    "quality_events",
                    "quality_gate_metrics",
                    "quality_result",
                ],
                metadata={"optional_read_keys": ["memory_context"]},
            ),
        ],
        edges=[
            EdgeSpec("collect-to-require", "collect_sources", "require_sources"),
            EdgeSpec("require-to-normalize", "require_sources", "normalize_sources"),
            EdgeSpec("normalize-to-dedupe", "normalize_sources", "deduplicate_sources"),
            EdgeSpec("dedupe-to-rank", "deduplicate_sources", "rank_sources"),
            EdgeSpec("rank-to-evidence", "rank_sources", "build_evidence"),
            EdgeSpec("evidence-to-draft", "build_evidence", "draft_report"),
            EdgeSpec("draft-to-quality", "draft_report", "quality_gate"),
        ],
        metadata={"profile": profile, "product_path": profile == PROFILE_LIVE},
    )


