from __future__ import annotations

from framework.harness.context.assembler import ContextAssembler
from framework.harness.context.budget import ContextBudgetEstimator, ContextBudgetUsage
from framework.harness.context.cache import ContextCachePolicyBuilder
from framework.harness.context.compatibility import context_payload
from framework.harness.context.compression import ContextCompressor
from framework.harness.context.compaction_models import (
    REVERSIBLE_CONTEXT_ACTIONS,
    ContextCompactionAction,
    ContextCompactionActionResult,
    ContextCompactionActionType,
    ContextCompactionOutcome,
    ContextCompactionPlan,
    ContextCompactionPolicy,
    ContextLossReport,
    ContextLossRisk,
)
from framework.harness.context.execution import (
    ContextCompactionActionExecutor,
    ContextCompactionExecutionResult,
    ContextCompactionExecutionStatus,
)
from framework.harness.context.fake import (
    FakeContextAssembler,
    FakeContextBudgetEstimator,
    FakeContextCachePolicyBuilder,
    FakeContextCompressor,
    FakeContextGateSuite,
    FakeContextRuntime,
    FakeContextSnapshotStore,
)
from framework.harness.context.gates import (
    ContextBudgetGate,
    ContextCacheKeyGate,
    ContextCompressionLossGate,
    ContextGateResult,
    ContextPrivacyGate,
    ContextProvenanceGate,
    ContextReplayGate,
    ContextSchemaPreservationGate,
    ContextSegmentOrderGate,
    ContextStablePrefixGate,
)
from framework.harness.context.models import (
    CONTEXT_SEGMENT_ORDER,
    CONTROL_PLANE_PRESERVED_FIELDS,
    CompressionRecord,
    ContextBudget,
    ContextCachePolicy,
    ContextCacheScope,
    ContextCompressionLevel,
    ContextCompressionSummary,
    ContextEnvelope,
    ContextSegment,
    ContextSegmentType,
    ContextSnapshot,
)
from framework.harness.context.group_models import (
    ContextGroup,
    ContextGroupKind,
    ContextGroupMember,
    ContextGroupMemberKind,
    ContextProtectionReason,
    ContextReconstructionPolicy,
    ContextToolTransactionState,
)
from framework.harness.context.materializer import (
    ContextGroupMaterializer,
    ContextGroupStructureValidator,
    ContextMaterializationRequest,
)
from framework.harness.context.planning import (
    ContextCompactionActionDefinition,
    ContextCompactionActionRegistry,
    ContextCompactionPlanner,
    ContextCompactionPlanningRequest,
    ContextCompactionPlanValidator,
    ContextCompactionPolicyResolver,
)
from framework.harness.context.planning_models import (
    ContextCompactionPlanningResult,
    ContextCompactionPlanningStatus,
    ContextPhysicalAdmissionEvidence,
    ContextPlanningBudgetUsage,
)
from framework.harness.context.snapshot import ContextSnapshotStore
from framework.harness.context.summary_models import (
    ContextSummaryCandidate,
    ContextSummaryClaim,
)
from framework.harness.context.summary import (
    ContextSummaryArtifactPort,
    ContextSummaryCandidateVerifier,
    ContextSummaryMaterializer,
    ContextSummaryRequest,
    ContextSummaryVerificationResult,
    ContextSummaryWorkerPort,
    ContextSummaryWorkerResult,
)
from framework.harness.context.verified_records import (
    ContextCompressionRecordV2,
    ContextSemanticSnapshot,
    ContextSemanticSnapshotKind,
)

__all__ = [
    "CONTEXT_SEGMENT_ORDER",
    "CONTROL_PLANE_PRESERVED_FIELDS",
    "CompressionRecord",
    "REVERSIBLE_CONTEXT_ACTIONS",
    "ContextAssembler",
    "ContextBudget",
    "ContextBudgetEstimator",
    "ContextBudgetGate",
    "ContextBudgetUsage",
    "ContextCacheKeyGate",
    "ContextCachePolicy",
    "ContextCachePolicyBuilder",
    "ContextCacheScope",
    "ContextCompressionLevel",
    "ContextCompressionSummary",
    "ContextCompressionLossGate",
    "ContextCompressor",
    "ContextCompactionAction",
    "ContextCompactionActionResult",
    "ContextCompactionActionType",
    "ContextCompactionActionExecutor",
    "ContextCompactionExecutionResult",
    "ContextCompactionExecutionStatus",
    "ContextCompactionActionDefinition",
    "ContextCompactionActionRegistry",
    "ContextCompactionPlanner",
    "ContextCompactionPlanningRequest",
    "ContextCompactionPlanningResult",
    "ContextCompactionPlanningStatus",
    "ContextCompactionPlanValidator",
    "ContextCompactionPolicyResolver",
    "ContextCompactionOutcome",
    "ContextCompactionPlan",
    "ContextCompactionPolicy",
    "ContextCompressionRecordV2",
    "ContextEnvelope",
    "ContextGateResult",
    "ContextPrivacyGate",
    "ContextPhysicalAdmissionEvidence",
    "ContextPlanningBudgetUsage",
    "ContextProvenanceGate",
    "ContextGroup",
    "ContextGroupKind",
    "ContextGroupMember",
    "ContextGroupMemberKind",
    "ContextGroupMaterializer",
    "ContextGroupStructureValidator",
    "ContextLossReport",
    "ContextLossRisk",
    "ContextMaterializationRequest",
    "ContextProtectionReason",
    "ContextReconstructionPolicy",
    "ContextReplayGate",
    "ContextSchemaPreservationGate",
    "ContextSegment",
    "ContextSegmentOrderGate",
    "ContextSegmentType",
    "ContextSnapshot",
    "ContextSnapshotStore",
    "ContextStablePrefixGate",
    "ContextSemanticSnapshot",
    "ContextSemanticSnapshotKind",
    "ContextSummaryCandidate",
    "ContextSummaryArtifactPort",
    "ContextSummaryCandidateVerifier",
    "ContextSummaryClaim",
    "ContextSummaryMaterializer",
    "ContextSummaryRequest",
    "ContextSummaryVerificationResult",
    "ContextSummaryWorkerPort",
    "ContextSummaryWorkerResult",
    "ContextToolTransactionState",
    "FakeContextAssembler",
    "FakeContextBudgetEstimator",
    "FakeContextCachePolicyBuilder",
    "FakeContextCompressor",
    "FakeContextGateSuite",
    "FakeContextRuntime",
    "FakeContextSnapshotStore",
    "context_payload",
]
