"""Role constants used by paper radar analysis agents."""

PAPER_ROLE_METADATA = "paper_metadata"
PAPER_ROLE_SOURCE_ARTIFACTS = "paper_source_artifacts"
PAPER_ROLE_SELECTION_DECISION = "paper_selection_decision"
PAPER_ROLE_SEMANTIC_SECTIONS = "paper_semantic_sections"
PAPER_ROLE_TAXONOMY_RESULT = "paper_taxonomy_result"
PAPER_ROLE_EXPERIMENT_RESULT = "paper_experiment_result"
PAPER_ROLE_BENCHMARK_CLAIMS = "paper_benchmark_claims"
PAPER_ROLE_EVIDENCE_VERIFICATION = "paper_evidence_verification"
PAPER_ROLE_CONTRIBUTION_RESULT = "paper_contribution_result"
PAPER_ROLE_QUALITY_RESULT = "paper_quality_result"
PAPER_ROLE_REPRODUCIBILITY_RESULT = "paper_reproducibility_result"
PAPER_ROLE_COMPARISON_RESULT = "paper_comparison_result"
PAPER_ROLE_PROFILE_DRAFT = "paper_profile_draft"
PAPER_ROLE_FINAL_PROFILE = "paper_final_profile"
PAPER_ROLE_MEMORY_RECORDS = "paper_memory_records"
PAPER_ROLE_READER_ANSWER = "paper_reader_answer"
PAPER_ROLE_REPAIR_HINT = "paper_repair_hint"
PAPER_ROLE_REVIEW_QUEUE_ITEM = "paper_review_queue_item"

PAPER_CORE_ROLES = (
    PAPER_ROLE_METADATA,
    PAPER_ROLE_SOURCE_ARTIFACTS,
    PAPER_ROLE_SELECTION_DECISION,
    PAPER_ROLE_SEMANTIC_SECTIONS,
    PAPER_ROLE_TAXONOMY_RESULT,
    PAPER_ROLE_EXPERIMENT_RESULT,
    PAPER_ROLE_BENCHMARK_CLAIMS,
    PAPER_ROLE_EVIDENCE_VERIFICATION,
    PAPER_ROLE_CONTRIBUTION_RESULT,
    PAPER_ROLE_QUALITY_RESULT,
    PAPER_ROLE_REPRODUCIBILITY_RESULT,
    PAPER_ROLE_COMPARISON_RESULT,
    PAPER_ROLE_PROFILE_DRAFT,
    PAPER_ROLE_FINAL_PROFILE,
    PAPER_ROLE_MEMORY_RECORDS,
    PAPER_ROLE_READER_ANSWER,
    PAPER_ROLE_REPAIR_HINT,
    PAPER_ROLE_REVIEW_QUEUE_ITEM,
)
